// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektKasse.Daten;

#nullable disable

namespace ProjektKasse.Migrations
{
    [DbContext(typeof(ProjektKasseContext))]
    [Migration("20240315092812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ProjektKasse.Model.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produkte");
                });

            modelBuilder.Entity("ProjektKasse.Model.Umsatz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Gebucht")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduktId");

                    b.ToTable("Umsätze");
                });

            modelBuilder.Entity("ProjektKasse.Model.Umsatz", b =>
                {
                    b.HasOne("ProjektKasse.Model.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");
                });
#pragma warning restore 612, 618
        }
    }
}
